import Foundation

enum AppLang: String, CaseIterable, Identifiable, Codable {
    case ru
    case en
    case de
    case es

    static let fallback: AppLang = .ru

    var id: String { rawValue }

    var title: String {
        switch self {
        case .ru: return "Русский"
        case .en: return "English"
        case .de: return "Deutsch"
        case .es: return "Español"
        }
    }

    var localeIdentifier: String {
        switch self {
        case .ru: return "ru_RU"
        case .en: return "en_US"
        case .de: return "de_DE"
        case .es: return "es_ES"
        }
    }
}

enum L10nKey: String, CaseIterable {
    case common_ok
    case common_cancel
    case common_delete

    case tab_today
    case tab_tasks
    case tab_pomodoro
    case tab_break
    case tab_health
    case tab_eye
    case tab_settings

    case auth_loading_restore
    case auth_error_title
    case auth_unknown_error
    case auth_brand_subtitle
    case auth_brand_description
    case auth_language_title
    case auth_language_hint
    case auth_mode_sign_in
    case auth_mode_sign_up
    case auth_mode_sign_in_subtitle
    case auth_mode_sign_up_subtitle
    case auth_mode_sign_in_button
    case auth_mode_sign_up_button
    case auth_field_name
    case auth_field_email
    case auth_field_password
    case auth_name_placeholder
    case auth_email_placeholder
    case auth_password_placeholder
    case auth_security_title
    case auth_security_description

    case settings_nav_title
    case settings_alert_clear_title
    case settings_alert_clear_message
    case settings_hero_title
    case settings_hero_subtitle
    case settings_stat_active
    case settings_stat_done
    case settings_account_title
    case settings_account_subtitle
    case settings_user_fallback
    case settings_session_inactive
    case settings_provider_email
    case settings_sign_out
    case settings_theme_title
    case settings_theme_subtitle
    case settings_theme_hint
    case settings_language_title
    case settings_language_subtitle
    case settings_language_hint
    case settings_data_title
    case settings_data_subtitle
    case settings_clear_tasks
}

protocol L10nModule {
    static var language: AppLang { get }
    static var table: [L10nKey: String] { get }
    static var tableLoose: [String: String] { get }
}

extension L10nModule {
    static var tableLoose: [String: String] { [:] }
}

enum L10n {
    static let storageKey = "app.language"

    private static let stringFallback: AppLang = .en

    private static let tables: [AppLang: [L10nKey: String]] = [
        L10nRU.language: L10nRU.table,
        L10nEN.language: L10nEN.table,
        L10nDE.language: L10nDE.table,
        L10nES.language: L10nES.table
    ]
    private static let looseTables: [AppLang: [String: String]] = [
        .ru: L10nRU.tableLoose.merging(extraLooseRU, uniquingKeysWith: { _, new in new }),
        .en: L10nEN.tableLoose.merging(extraLooseEN, uniquingKeysWith: { _, new in new }),
        .de: L10nDE.tableLoose.merging(extraLooseDE, uniquingKeysWith: { _, new in new }),
        .es: L10nES.tableLoose.merging(extraLooseES, uniquingKeysWith: { _, new in new })
    ]

    static func lang(from rawValue: String) -> AppLang {
        AppLang(rawValue: rawValue) ?? .fallback
    }

    static var currentLang: AppLang {
        let raw = UserDefaults.standard.string(forKey: storageKey) ?? AppLang.fallback.rawValue
        return lang(from: raw)
    }

    static func tr(_ key: L10nKey, _ lang: AppLang) -> String {
        tables[lang]?[key]
        ?? tables[.fallback]?[key]
        ?? key.rawValue
    }

    static func tr(_ key: String, _ lang: AppLang) -> String {
        looseTables[lang]?[key]
        ?? looseTables[stringFallback]?[key]
        ?? looseTables[.fallback]?[key]
        ?? humanizedFallback(key, lang)
    }

    static func trCurrent(_ key: String) -> String {
        tr(key, currentLang)
    }

    static func fmt(_ key: String, _ lang: AppLang, _ args: [CVarArg]) -> String {
        let template = tr(key, lang)
        return String(format: template, locale: Locale(identifier: lang.localeIdentifier), arguments: args)
    }

    static func fmt(_ key: String, _ lang: AppLang, _ args: CVarArg...) -> String {
        fmt(key, lang, args)
    }

    static func fmtCurrent(_ key: String, _ args: [CVarArg]) -> String {
        fmt(key, currentLang, args)
    }

    static func fmtCurrent(_ key: String, _ args: CVarArg...) -> String {
        fmtCurrent(key, args)
    }

    private static func humanizedFallback(_ key: String, _ lang: AppLang) -> String {
        let last = key.split(separator: ".").last.map(String.init) ?? key
        let normalized = last.replacingOccurrences(of: "_", with: " ")
        if lang == .ru {
            return normalized
                .replacingOccurrences(of: "title", with: "заголовок")
                .replacingOccurrences(of: "subtitle", with: "подзаголовок")
                .replacingOccurrences(of: "button", with: "кнопка")
                .replacingOccurrences(of: "save", with: "сохранить")
        }
        return normalized.capitalized
    }

    private static let extraLooseRU: [String: String] = [
        "today.greeting.morning": "Доброе утро",
        "today.greeting.day": "Добрый день",
        "today.greeting.evening": "Добрый вечер",
        "today.nav_title": "Органайзер",
        "today.toolbar.new_task": "Новая задача",
        "today.header.subtitle": "Планируй день и держи ритм без перегруза",
        "today.header.done_count": "%d выполнено",
        "today.metric.active": "Активные",
        "today.metric.streak": "Серия",
        "today.metric.done": "Выполнено",
        "today.chip.focus": "Фокус",
        "today.chip.selfcare": "Забота о себе",
        "today.progress.day": "день",
        "today.next.title": "Ближайшая задача",
        "today.next.subtitle": "Что важно сделать следующим",
        "today.next.to_island": "В остров",
        "today.next.no_due": "Без срока",
        "today.next.empty_title": "Нет предстоящих задач",
        "today.next.empty_button": "Добавить первую задачу",
        "today.quick.title": "Быстрые действия",
        "today.quick.subtitle": "Частые сценарии одним касанием",
        "today.quick.today": "Сегодня",
        "today.quick.new": "Новая",
        "today.quick.done": "Готово",
        "today.quick.eyes": "Глаза",

        "tasks.nav_title": "Задачи",
        "tasks.search_prompt": "Поиск задач",
        "tasks.section_active": "Активные",
        "tasks.section_done": "Выполненные",
        "tasks.control.summary": "Сводка",
        "tasks.control.subtitle": "Активные и выполненные задачи",
        "tasks.badge.active": "%d активн.",
        "tasks.badge.done": "%d готово",
        "tasks.info.subtitle": "Управляй приоритетами и держи фокус дня под контролем",
        "tasks.sort.by_due": "По сроку",
        "tasks.sort.by_date": "По дате",
        "tasks.empty.title": "Пока здесь пусто",
        "tasks.empty.subtitle": "Добавь первую задачу — и день станет собраннее.",
        "tasks.empty.button": "Создать задачу",
        "tasks.swipe.delete": "Удалить",
        "tasks.swipe.restore": "Вернуть",
        "tasks.swipe.done": "Готово",
        "tasks.menu.make_active": "Сделать активной",
        "tasks.menu.mark_done": "Отметить выполненной",
        "tasks.menu.edit": "Редактировать",
        "tasks.menu.delete": "Удалить",
        "tasks.due.today": "Сегодня %@",
        "tasks.due.tomorrow": "Завтра %@",

        "task_editor.main.title": "Основное",
        "task_editor.main.subtitle": "Название и заметки задачи",
        "task_editor.main.name": "Название",
        "task_editor.main.name_placeholder": "Например: Сдать отчёт",
        "task_editor.main.notes": "Заметки",
        "task_editor.due.title": "Срок",
        "task_editor.due.subtitle": "Дата и время выполнения",
        "task_editor.due.toggle": "Установить срок",
        "task_editor.category.title": "Категория",
        "task_editor.category.subtitle": "Контекст для задачи",
        "task_editor.category.picker": "Категория",
        "task_editor.nav.edit": "Редактировать",
        "task_editor.nav.new": "Новая задача",
        "task_editor.cancel": "Отмена",
        "task_editor.save_changes": "Сохранить изменения",
        "task_editor.save": "Сохранить",
        "task_editor.hero.edit": "Редактирование",
        "task_editor.hero.edit_subtitle": "Обнови детали — и продолжай фокус.",
        "task_editor.hero.new": "Создание задачи",
        "task_editor.hero.new_subtitle": "Заполни коротко, остальное добавишь позже.",

        "pomodoro.nav_title": "Помодоро",
        "pomodoro.hero.title": "Помодоро",
        "pomodoro.round": "Раунд %d",
        "pomodoro.paused.title": "На паузе",
        "pomodoro.paused.subtitle": "Можно продолжить",
        "pomodoro.ready.title": "Готов к старту",
        "pomodoro.ready.subtitle": "25 минут фокуса",
        "pomodoro.quick.title": "Быстрый старт",
        "pomodoro.quick.subtitle": "Готовые пресеты фокуса",
        "pomodoro.quick.break": "Перерыв",
        "pomodoro.custom.title": "Свой таймер",
        "pomodoro.custom.subtitle": "Ручная длительность сессии",
        "pomodoro.custom.placeholder": "Мин",
        "pomodoro.custom.minutes_unit": "мин",
        "pomodoro.custom.start": "Старт",
        "pomodoro.custom.range": "Диапазон: 1–180 минут",
        "pomodoro.transport.title": "Управление",
        "pomodoro.transport.subtitle": "Пауза, продолжение и сброс",
        "pomodoro.transport.pause": "Пауза",
        "pomodoro.transport.resume": "Продолжить",
        "pomodoro.transport.stop": "Стоп",
        "pomodoro.remaining": "Осталось %d:%02d",
        "pomodoro.phase.focus": "Фокус",
        "pomodoro.phase.short_break": "Перерыв",
        "pomodoro.phase.long_break": "Большой перерыв",
        "pomodoro.phase.long_break_short": "Большой",
        "pomodoro.phase.paused": "Пауза",
        "pomodoro.phase.stopped": "Стоп",
        "pomodoro.notification.focus_body": "Время поработать",
        "pomodoro.notification.short_break_body": "Сделай растяжку и отдохни",
        "pomodoro.notification.long_break_body": "Подыши, пройдись, попей воды",
        "pomodoro.alarm.title": "Таймер завершён",
        "pomodoro.alarm.subtitle": "Этап: %@",
        "pomodoro.alarm.stop": "Выключить",

        "break.nav_title": "Перерыв",
        "break.hero.title": "Мини-игра перерыва",
        "break.hero.subtitle": "Платформер в стиле классических раннеров",
        "break.hero.description": "Собирай монеты, перепрыгивай препятствия и доберись до флага. Это быстрый перерыв между задачами.",
        "break.hud.record": "Рекорд",
        "break.hud.goal": "Цель",
        "break.hud.goal_value": "12 монет",
        "break.hud.distance": "Дистанция",
        "break.hud.distance_value": "3400",
        "break.launch.title": "Запуск мини-игры",
        "break.launch.subtitle": "Откроется на весь экран",
        "break.launch.description": "Нажми «Запустить», чтобы играть в полноэкранном режиме.",
        "break.launch.button": "Запустить на весь экран",
        "break.hints.title": "Как играть",
        "break.hints.subtitle": "Коротко перед стартом",
        "break.hints.step1": "1. Удерживай «Влево/Вправо» для движения.",
        "break.hints.step2": "2. Нажимай «Прыжок», чтобы перепрыгнуть шипы и провалы.",
        "break.hints.step3": "3. Собери максимум монет и добеги до флага.",
        "break.close": "Закрыть",
        "break.hud.coins": "Монеты",
        "break.hud.lives": "Жизни",
        "break.hud.time": "Время",
        "break.hud.progress": "Прогресс",
        "break.reset": "Сброс",
        "break.controls.left": "Влево",
        "break.controls.right": "Вправо",
        "break.controls.jump": "Прыжок",
        "break.controls.play": "Играть",
        "break.controls.pause": "Пауза",
        "break.overlay.ready_title": "Готов к забегу",
        "break.overlay.paused_title": "Пауза",
        "break.overlay.won_title": "Финиш!",
        "break.overlay.lost_title": "Игра окончена",
        "break.overlay.ready_subtitle": "Собери как можно больше монет и не теряй все жизни.",
        "break.overlay.paused_subtitle": "Можно продолжить с текущего места или начать заново.",
        "break.overlay.won_subtitle": "Монеты: %d/%d • Время: %@",
        "break.overlay.lost_subtitle": "Монеты: %d/%d. Попробуй ещё раз.",
        "break.overlay.start": "Старт",
        "break.overlay.resume": "Продолжить",
        "break.overlay.play_again": "Играть снова",
        "break.breathing.title": "Дыхание и восстановление",
        "break.breathing.subtitle": "Плавный ритм для спокойствия",
        "break.breathing.description": "Выбери режим и следуй анимации: это помогает снизить напряжение, выровнять пульс и восстановить дыхание.",
        "break.breathing.preset.balance": "Баланс",
        "break.breathing.preset.recovery": "Восстановление",
        "break.breathing.phase.inhale": "Вдох",
        "break.breathing.phase.hold": "Пауза",
        "break.breathing.phase.exhale": "Выдох",
        "break.breathing.phase.rest": "Отдых",
        "break.breathing.hint.inhale": "Вдыхай через нос и поднимай грудную клетку мягко.",
        "break.breathing.hint.hold": "Небольшая пауза без напряжения.",
        "break.breathing.hint.exhale": "Выдыхай медленнее, чем вдыхал.",
        "break.breathing.hint.rest": "Расслабь плечи и челюсть.",
        "break.breathing.cycle": "Цикл",
        "break.breathing.rate": "Ритм",
        "break.breathing.rate_value": "%d дых/мин",
        "break.breathing.button.start": "Начать",
        "break.breathing.button.pause": "Пауза",
        "break.breathing.button.reset": "Сброс",
        "health.analytics.title": "Аналитика дыхания",
        "health.analytics.subtitle": "Короткая статистика сессий",
        "health.analytics.sessions": "Сессии",
        "health.analytics.minutes": "Минуты",
        "health.analytics.avg_cycles": "Сред. циклы",
        "health.analytics.this_week": "Эта неделя",
        "health.analytics.last_session": "Последняя сессия",
        "health.analytics.minutes_value": "%d мин",
        "health.analytics.empty": "Пока нет данных. Проведи первую дыхательную сессию.",
        "health.voice.title": "Голосовой помощник",
        "health.voice.subtitle": "Озвучивание аналитики и рекомендаций",
        "health.voice.description": "Короткий голосовой отчёт по дыханию: текущая динамика и что улучшить дальше.",
        "health.voice.recommendations_title": "Рекомендации",
        "health.voice.button.play": "Озвучить аналитику",
        "health.voice.button.stop": "Остановить",
        "health.voice.status.ready": "Готов к озвучке",
        "health.voice.status.speaking": "Озвучивание в процессе",
        "health.voice.disabled_hint": "Голосовой помощник выключен. Включи его в Настройках -> Здоровье.",
        "health.voice.recommendation.first_session": "Начни с 2-3 коротких сессий по 2-4 минуты в день.",
        "health.voice.recommendation.short_cycle": "Держи ровный ритм: вдох 4 секунды, выдох 6 секунд.",
        "health.voice.recommendation.weekly_minutes": "Увеличь недельный объём дыхательной практики хотя бы до 12-15 минут.",
        "health.voice.recommendation.extend_exhale": "Добавь чуть более длинный выдох, чтобы быстрее снижать напряжение.",
        "health.voice.recommendation.regularity": "Сохраняй регулярность: лучше короткая ежедневная сессия, чем редкая длинная.",
        "health.voice.recommendation.keep_it_up": "Текущий ритм хороший. Поддерживай его в те же часы дня.",
        "health.voice.recommendation.progressive": "Для прогресса добавь ещё один спокойный цикл в каждую сессию.",
        "health.voice.report.empty": "Пока нет данных по дыхательным сессиям.",
        "health.voice.report.summary": "За всё время: %d сессий, %d минут, в среднем %d циклов.",
        "health.voice.report.weekly": "За эту неделю: %d минут дыхания.",
        "health.voice.report.last_session": "Последняя сессия: %@.",
        "health.voice.report.recommendations_intro": "Рекомендации:",
        "health.voice.speed.calm": "Спокойная",
        "health.voice.speed.balanced": "Стандартная",
        "health.voice.speed.energetic": "Быстрая",
        "settings.voice.title": "Голосовой помощник",
        "settings.voice.subtitle": "Озвучивание аналитики раздела здоровья",
        "settings.voice.enabled_title": "Включить помощника",
        "settings.voice.enabled_subtitle": "Использовать системный голос iPhone для отчётов",
        "settings.voice.auto_title": "Автоозвучка при открытии",
        "settings.voice.auto_subtitle": "Автоматически читать отчёт при входе во вкладку «Здоровье»",
        "settings.voice.speed_title": "Скорость речи",
        "settings.voice.speed_subtitle": "Подбери темп, который удобно слушать",
        "settings.voice.model_title": "Голосовая модель",
        "settings.voice.model_subtitle": "Выбор голоса. Авто-режим ставит самый естественный доступный вариант",
        "settings.voice.model_auto": "Авто (лучший доступный)",
        "settings.voice.preview": "Прослушать",
        "settings.voice.stop": "Стоп",
        "settings.voice.preview_text": "Проверка голосового помощника. Аналитика и рекомендации будут озвучены в выбранном темпе.",
        "settings.voice.disabled_hint": "Включи помощника, чтобы активировать предпросмотр и автоозвучку.",

        "stats.metric.focus": "Фокус",
        "stats.metric.tasks": "Задачи",
        "stats.metric.both": "Оба",
        "stats.header.title": "Статистика",
        "stats.header.subtitle": "Тренд фокуса и задач",
        "stats.window.7": "7д",
        "stats.window.30": "30д",
        "stats.kpi.focus_minutes": "Фокус, мин",
        "stats.kpi.tasks": "Задачи",
        "stats.kpi.streak_days": "Серия дней",
        "stats.kpi.avg_focus": "Сред. фокус",
        "stats.axis.date": "Дата",
        "stats.axis.focus_minutes": "Фокус, мин",
        "stats.axis.tasks": "Задачи",
        "stats.axis.selected_date": "Выбранная дата",
        "stats.footer.hint": "Нажми на график, чтобы увидеть подробности дня",
        "stats.event.focus": "Фокус",
        "stats.event.task_done": "Задача",
        "stats.minutes": "%d мин",
        "stats.hours": "%d ч",
        "stats.hours_minutes": "%d ч %d мин",
        "stats.day.summary.focus_and_tasks": "%@ • %d выполн.",
        "stats.day.summary.focus_only": "%@ фокуса",
        "stats.day.summary.tasks_only": "%d выполн.",
        "stats.day.summary.none": "Нет активности",

        "countdown.default_title": "Событие",
        "countdown.accessibility": "Отсчёт до события",
        "countdown.header.title": "Отсчёт до события",
        "countdown.header.subtitle": "Живой таймер до важной даты",
        "countdown.event_reached": "Событие наступило",
        "countdown.stats.days": "%d дн.",
        "countdown.stats.hours": "%d ч.",
        "countdown.actions.to_island": "В остров",
        "countdown.actions.reset": "Сбросить",
        "countdown.empty.title": "Отсчёт до события",
        "countdown.empty.subtitle": "Ещё не задано событие. Зайди в «Настройки → Отсчёт до события».",

        "daily.default_title": "Работа",
        "daily.notification.test_title": "Тест напоминания",
        "daily.notification.test_body": "Это тестовое уведомление",
        "daily.notification.work_title": "Пора работать",
        "daily.notification.prep_title": "Пора готовиться",
        "daily.notification.prep_body": "Через %d мин: %@",

        "task.notification.reminder": "Напоминание",
        "movement.notification.title": "Двигательная пауза",
        "movement.tip.1": "Встань, раскатай плечи 10 раз и потяни шею.",
        "movement.tip.2": "Сделай 15 приседаний и пройди 200 шагов.",
        "movement.tip.3": "Подыши 1 минуту: 4–4–6, затем потяни спину.",
        "movement.tip.4": "Круговые движения кистями и стопами по 20 раз.",
        "movement.tip.5": "Планка 30 сек + вода.",
        "movement.tip.fallback": "Встань и разомнись минуту.",

        "task.category.work.title": "Работа",
        "task.category.work.subtitle": "Фокус и дедлайны",
        "task.category.study.title": "Учёба",
        "task.category.study.subtitle": "Навыки и рост",
        "task.category.health.title": "Здоровье",
        "task.category.health.subtitle": "Тело и энергия",
        "task.category.rest.title": "Отдых",
        "task.category.rest.subtitle": "Восстановление",
        "task.category.home.title": "Дом",
        "task.category.home.subtitle": "Быт и порядок",
        "task.category.other.title": "Другое",
        "task.category.other.subtitle": "Разное",

        "alarm.default_label": "Подъём",
        "alarm.notification.main_title": "Будильник",
        "alarm.notification.prep_title": "Скоро будильник",
        "alarm.notification.prep_body": "Через %d мин: %@",
        "alarm.notification.test_title": "Тест будильника",
        "alarm.notification.test_body": "Это тестовое уведомление",
        "alarm.settings.toggle": "Включить будильник",
        "alarm.settings.label_placeholder": "Подпись",
        "alarm.settings.time": "Время",
        "alarm.settings.prep": "Подготовка за %d мин",
        "alarm.settings.save": "Сохранить и назначить",
        "alarm.settings.test": "Тест через 3с",
        "alarm.settings.info": "Будет 1–2 уведомления каждый день: «Скоро будильник» (если задано) и «Будильник» в указанное время.",

        "settings.quick.title": "Быстрые действия",
        "settings.quick.subtitle": "Частые сценарии одним тапом",
        "settings.quick.reminders_on": "Напоминания включены",
        "settings.quick.reminders_off": "Напоминания выключены",
        "settings.quick.reminders_subtitle": "Ежедневные уведомления",
        "settings.quick.eyes_on": "Гимнастика включена",
        "settings.quick.eyes_off": "Гимнастика выключена",
        "settings.quick.eyes_subtitle": "Автопредложение",
        "settings.quick.preset_title": "Пресет 25/5/15",
        "settings.quick.preset_subtitle": "Классический Pomodoro",
        "settings.quick.test_title": "Тест уведомления",
        "settings.quick.test_subtitle": "Через 3 секунды",

        "settings.live.title": "Live Activities",
        "settings.live.subtitle": "Dynamic Island и активные таймеры",
        "settings.live.end_all_title": "Закрыть все активности",
        "settings.live.end_all_subtitle": "Убрать все активные таймеры",
        "settings.live.test_title": "Показать тест 15 сек",
        "settings.live.test_subtitle": "Проверка отображения Dynamic Island",
        "settings.live.test_session_title": "Тест",
        "settings.live.open_notifications_title": "Открыть настройки уведомлений",
        "settings.live.open_notifications_subtitle": "Разрешения и баннеры",
        "settings.live.requirement": "Нужен iPhone с Dynamic Island и установленный Widget Extension.",
        "settings.live.ios_required": "Требуется iOS 16.2+",
        "settings.scope.title": "Быстрая навигация",
        "settings.scope.subtitle": "Показывай только нужные разделы",
        "settings.scope.all": "Все",
        "settings.scope.account": "Профиль",
        "settings.scope.focus": "Фокус",
        "settings.scope.health": "Здоровье",
        "settings.scope.data": "Данные",

        "settings.pomodoro.title": "Помодоро",
        "settings.pomodoro.subtitle": "Ритм фокуса и перерывов",
        "settings.pomodoro.focus_title": "Фокус",
        "settings.pomodoro.focus_subtitle": "Основная сессия",
        "settings.pomodoro.short_break_title": "Перерыв",
        "settings.pomodoro.short_break_subtitle": "Короткая пауза",
        "settings.pomodoro.long_break_title": "Длинный перерыв",
        "settings.pomodoro.long_break_subtitle": "После серии фокуса",
        "settings.pomodoro.rounds_title": "Раундов до длинного",
        "settings.pomodoro.rounds_subtitle": "Сколько фокусов подряд",
        "settings.pomodoro.ringtone_title": "Рингтон завершения",
        "settings.pomodoro.ringtone_subtitle": "Звук при окончании таймера",
        "settings.pomodoro.ringtone_preview": "Прослушать",
        "settings.pomodoro.ringtone.radar": "Радар",
        "settings.pomodoro.ringtone.beacon": "Маяк",
        "settings.pomodoro.ringtone.chime": "Перезвон",
        "settings.pomodoro.ringtone.signal": "Сигнал",

        "settings.daily.title": "Ежедневные напоминания",
        "settings.daily.subtitle": "Автоматические уведомления по расписанию",
        "settings.daily.toggle_title": "Включить",
        "settings.daily.toggle_subtitle": "Два уведомления в день",
        "settings.daily.name_title": "Название (что делать)",
        "settings.daily.name_placeholder": "Например: Учиться / Тренировка / Работа",
        "settings.daily.start_time": "Время начала",
        "settings.daily.preparation": "Подготовка",
        "settings.daily.preparation_value": "за %d мин",
        "settings.daily.save": "Сохранить и назначить",
        "settings.daily.test": "Тест 3с",
        "settings.daily.info": "Каждый день придут два уведомления: заранее «Пора готовиться» и в указанное время «Пора работать».",

        "settings.eye.title": "Гимнастика для глаз",
        "settings.eye.subtitle": "Мягкие подсказки и параметры тренировки",
        "settings.eye.toggle_title": "Автопредложение после долгой работы",
        "settings.eye.toggle_subtitle": "Появится мягкий prompt",
        "settings.eye.threshold": "Порог",
        "settings.eye.threshold_value": "%d мин подряд",
        "settings.eye.targets": "Целей за сессию",
        "settings.eye.limit": "Лимит на цель",
        "settings.eye.cooldown": "Кулдаун предложений",
        "settings.eye.open_now": "Открыть тренировку сейчас",

        "settings.countdown.title": "Отсчёт до события",
        "settings.countdown.subtitle": "Название и дата важного события",
        "settings.countdown.hint": "Настрой событие, чтобы видеть живой обратный отсчёт на главном экране.",
        "settings.countdown.name_placeholder": "Название события",
        "settings.countdown.date_time": "Дата и время",
        "settings.countdown.default_event_title": "Событие",
        "settings.countdown.save": "Сохранить",
        "settings.countdown.reset": "Сбросить",
        "settings.countdown.current": "Текущее событие",
        "settings.countdown.current_value": "«%@» — %@",
        "settings.countdown.empty": "Событие пока не задано",

        "settings.unit.minutes": "%d мин",
        "settings.unit.seconds": "%d сек",

        "eye.mode.classic": "Классика",
        "eye.mode.moving": "Движение",
        "eye.mode.color": "Цвет",
        "eye.mode.peripheral": "Периферия",
        "eye.mode.tracking": "Слежение",
        "eye.achievement.first_session": "Первая тренировка",
        "eye.achievement.ten_hits_streak": "10 попаданий подряд",
        "eye.achievement.sub_200ms": "Реакция < 200 мс",
        "eye.achievement.no_miss": "0 промахов",
        "eye.achievement.five_days": "5 дней подряд",
        "eye.achievement.pro_hawk": "Орлиный глаз",
        "eye.achievement.unlocked": "Получено",
        "eye.achievement.locked": "Не получено",
        "eye.chart.empty": "Нет данных для графика",
        "eye.chart.not_available": "Charts не подключён",
        "eye.chart.session": "Сессия",
        "eye.chart.seconds": "с",
        "eye.common.done": "Готово",
        "eye.common.cancel": "Отмена",
        "eye.common.save": "Сохранить",
        "eye.common.em_dash": "—",
        "eye.unit.ms": "%d мс",

        "eye.game.title": "Гимнастика для глаз",
        "eye.game.streak": "Стрик: %d",
        "eye.game.left_seconds": "%dс",
        "eye.game.intro.title": "Выбери режим и жми Начать",
        "eye.game.intro.subtitle": "Классика — точка появляется в разных местах. Другие режимы добавляют движение, цвета, периферию и слежение.",
        "eye.game.intro.targets": "%d целей",
        "eye.game.intro.seconds_per_target": "%d сек/цель",
        "eye.game.break.title": "Перерыв для глаз",
        "eye.game.break.subtitle": "Посмотри вдаль через окно 20 секунд. Часто моргай, сделай круговые движения глазами.",
        "eye.game.break.left": "Осталось: %dс",
        "eye.game.break.skip": "Пропустить",
        "eye.game.summary.title": "Готово!",
        "eye.game.summary.hits_misses": "Попадания: %d • Промахи: %d",
        "eye.game.summary.reaction": "Средняя реакция: %@ • Лучшая: %@ • Лучший стрик: %d",
        "eye.game.start": "Начать",
        "eye.game.later": "Позже",
        "eye.game.targets_progress": "Целей: %d/%d",
        "eye.game.hits": "Попадания: %d",
        "eye.game.misses": "Промахи: %d",
        "eye.game.resume": "Продолжить",
        "eye.game.pause": "Пауза",
        "eye.game.finish": "Завершить",
        "eye.game.again": "Ещё раз",
        "eye.game.done": "Готово",

        "eye.home.nav_title": "Глаза",
        "eye.home.trainer_title": "Тренажёр",
        "eye.home.header_title": "Здоровье глаз",
        "eye.home.header_subtitle": "Фокус, реакция и профилактика усталости",
        "eye.home.goal_done": "Цель недели выполнена",
        "eye.home.goal_left": "До цели: %d",
        "eye.home.metric_streak": "Серия",
        "eye.home.metric_week": "Неделя",
        "eye.home.metric_achievements": "Достижения",
        "eye.home.days_short": "%d дн",
        "eye.home.week_activity": "Активность недели",
        "eye.home.goal_done_subtitle": "Отлично! Недельная цель закрыта.",
        "eye.home.goal_remaining_subtitle": "Осталось %d тренировок до недельной цели.",
        "eye.home.quick_title": "Быстрый старт",
        "eye.home.quick_subtitle": "Короткая сессия за один тап",
        "eye.home.settings": "Настройки",
        "eye.home.quick_description": "Короткая сессия на %d целей. Лучше тренироваться регулярно, чем долго.",
        "eye.home.start_training": "Начать тренировку",
        "eye.home.stats": "Статистика",
        "eye.home.progress_title": "Прогресс",
        "eye.home.progress_subtitle": "Стрик и динамика реакции",
        "eye.home.streak_days": "Серия %d дн.",
        "eye.home.last": "Последняя",
        "eye.home.hits": "попаданий",
        "eye.home.avg_reaction": "Средняя реакция",
        "eye.home.best_streak": "Лучший стрик",
        "eye.home.in_row": "подряд",
        "eye.home.empty_training": "Ещё нет тренировок. Нажми «Начать тренировку».",
        "eye.home.achievements_title": "Достижения",
        "eye.home.achievements_subtitle": "Личные milestones",
        "eye.home.achievements_hint": "Открывай ачивки регулярными короткими сессиями.",
        "eye.home.tips_title": "Советы",
        "eye.home.tips_subtitle": "Мини-привычки против усталости",
        "eye.home.tips_intro": "Мини-привычки, которые заметно снижают усталость глаз.",
        "eye.home.tip_1": "Правило 20–20–20: каждые 20 минут смотри на объект в 20 футах (≈6 м) в течение 20 секунд.",
        "eye.home.tip_2": "Следи за освещением: избегай бликов и слишком тусклых экранов.",
        "eye.home.tip_3": "Чаще моргай: это снижает сухость и напряжение.",
        "eye.home.tip_4": "Делай разминку плеч и шеи — это улучшает кровоток.",

        "eye.stats.nav_title": "Статистика",
        "eye.stats.totals_title": "Итоги",
        "eye.stats.totals_subtitle": "Общая статистика тренировок",
        "eye.stats.sessions": "Сессий",
        "eye.stats.hits": "Попадания",
        "eye.stats.misses": "Промахи",
        "eye.stats.best_streak": "Лучший стрик",
        "eye.stats.avg_reaction": "Средняя реакция",
        "eye.stats.sessions_title": "Сессии",
        "eye.stats.sessions_subtitle": "История последних запусков",
        "eye.stats.history_empty": "История пуста",
        "eye.stats.result": "Результат %d/%d",
        "eye.stats.misses_value": "Промахи %d",
        "eye.stats.streak_value": "Стрик %d",
        "eye.stats.avg_value": "Avg %@",

        "eye.settings.nav_title": "Настройки глаз",
        "eye.settings.profile_title": "Профиль тренировки",
        "eye.settings.profile_subtitle": "Параметры можно изменить в любой момент",
        "eye.settings.targets_value": "%d целей",
        "eye.settings.seconds_short_value": "%@ c",
        "eye.settings.session_title": "Сессия",
        "eye.settings.session_subtitle": "Базовая длительность и размер целей",
        "eye.settings.targets_per_session": "Целей за сессию",
        "eye.settings.time_per_target": "Время на цель",
        "eye.settings.dot_size": "Размер точки",
        "eye.settings.adaptive_title": "Адаптация сложности",
        "eye.settings.adaptive_subtitle": "Динамическая подстройка по ходу сессии",
        "eye.settings.adaptive_toggle": "Включить адаптацию",
        "eye.settings.adaptive_toggle_subtitle": "Усложнять при стабильных попаданиях",
        "eye.settings.adaptive_step": "Шаг усложнения",
        "eye.settings.adaptive_step_value": "Каждые %d попаданий",
        "eye.settings.min_size": "Минимальный размер",
        "eye.settings.min_time": "Минимальное время",
        "eye.settings.modes_title": "Режимы",
        "eye.settings.modes_subtitle": "Какие механики доступны в тренировке",
        "eye.settings.breaks_title": "Перерывы",
        "eye.settings.breaks_subtitle": "Восстановление глаз между сериями",
        "eye.settings.breaks_toggle": "Напоминать о перерывах",
        "eye.settings.breaks_toggle_subtitle": "Пауза после заданного числа целей",
        "eye.settings.breaks_frequency": "Частота перерывов",
        "eye.settings.breaks_frequency_value": "Каждые %d целей",
        "eye.settings.breaks_duration": "Длительность",
        "eye.settings.seconds_value": "%d c",
        "eye.settings.auto_title": "Автопредложение",
        "eye.settings.auto_subtitle": "Автоматический запуск тренировки после фокуса",
        "eye.settings.auto_toggle": "Предлагать после долгой работы",
        "eye.settings.auto_toggle_subtitle": "Открывать мягкий prompt",
        "eye.settings.auto_threshold": "Порог",
        "eye.settings.auto_cooldown": "Кулдаун повтора",
        "eye.settings.feedback_title": "Обратная связь",
        "eye.settings.feedback_subtitle": "Звук и тактильные отклики",
        "eye.settings.sound": "Звук",
        "eye.settings.haptics": "Хаптика",
        "eye.settings.save_settings": "Сохранить настройки",

        "assistant.title": "Голосовой помощник",
        "assistant.subtitle": "Управление задачами и функциями голосом",
        "assistant.description": "Скажите команду: добавить задачу, открыть раздел, запустить или остановить помодоро.",
        "assistant.state.ready": "Готов к командам",
        "assistant.state.listening": "Слушаю...",
        "assistant.state.processing": "Обрабатываю...",
        "assistant.state.speaking": "Отвечаю голосом...",
        "assistant.state.error": "Ошибка: %@",
        "assistant.transcript.title": "Распознанная команда",
        "assistant.transcript.empty": "Команда появится здесь после записи.",
        "assistant.response.title": "Ответ помощника",
        "assistant.response.unknown": "Не понял команду. Попробуйте: «Открой задачи».",
        "assistant.quick.title": "Быстрые команды",
        "assistant.quick.add": "Добавь задачу проверить почту",
        "assistant.quick.tasks": "Открой задачи",
        "assistant.quick.summary": "Сводка показателей за неделю",
        "assistant.quick.pomodoro": "Запусти помодоро на 25 минут",
        "assistant.quick.pause": "Поставь помодоро на паузу",
        "assistant.quick.resume": "Продолжи помодоро",
        "assistant.quick.break": "Запусти короткий перерыв",
        "assistant.quick.eye": "Запусти тренировку глаз",
        "assistant.suggested.title": "Рекомендации для вас",
        "assistant.suggested.personalized": "Подобрано по вашим привычкам и последним действиям.",
        "assistant.suggested.learning": "Помощник изучает ваши сценарии и скоро персонализирует предложения.",
        "assistant.hint.tap_hold": "Тап по кнопке ассистента начинает запись. Удержание открывает полное меню.",
        "assistant.button.start": "Начать запись",
        "assistant.button.stop": "Готово",
        "assistant.button.close": "Закрыть",
        "assistant.permission.speech": "Разрешите распознавание речи в настройках iPhone.",
        "assistant.permission.mic": "Разрешите доступ к микрофону в настройках iPhone.",
        "assistant.permission.unavailable": "Распознавание речи сейчас недоступно.",
        "assistant.response.task_added": "Добавил задачу: %@.",
        "assistant.response.task_completed": "Отметил задачу выполненной: %@.",
        "assistant.response.task_deleted": "Удалил задачу: %@.",
        "assistant.response.task_not_found": "Не нашёл подходящую задачу.",
        "assistant.response.tab_opened": "Открываю раздел: %@.",
        "assistant.response.pomodoro_started": "Запустил фокус на %d минут.",
        "assistant.response.pomodoro_paused": "Поставил помодоро на паузу.",
        "assistant.response.pomodoro_resumed": "Продолжаю помодоро.",
        "assistant.response.short_break_started": "Запустил короткий перерыв.",
        "assistant.response.long_break_started": "Запустил длинный перерыв.",
        "assistant.response.pomodoro_stopped": "Помодоро остановлен.",
        "assistant.response.eye_opened": "Открываю тренировку для глаз.",
        "assistant.response.metrics_today": "Сегодня: %@ фокуса и %d выполненных задач.",
        "assistant.response.metrics_week": "За 7 дней: %@ фокуса и %d выполненных задач.",
        "assistant.response.metrics_active": "Сейчас активных задач: %d.",
        "assistant.response.metrics_streak": "Серия продуктивных дней: %d."
    ]

    private static let extraLooseEN: [String: String] = [
        "today.greeting.morning": "Good morning",
        "today.greeting.day": "Good afternoon",
        "today.greeting.evening": "Good evening",
        "today.nav_title": "Organizer",
        "today.toolbar.new_task": "New task",
        "today.header.subtitle": "Plan your day and keep a steady pace",
        "today.header.done_count": "%d done",
        "today.metric.active": "Active",
        "today.metric.streak": "Streak",
        "today.metric.done": "Done",
        "today.chip.focus": "Focus",
        "today.chip.selfcare": "Self care",
        "today.progress.day": "day",
        "today.next.title": "Next task",
        "today.next.subtitle": "What matters most next",
        "today.next.to_island": "To Island",
        "today.next.no_due": "No due date",
        "today.next.empty_title": "No upcoming tasks",
        "today.next.empty_button": "Add first task",
        "today.quick.title": "Quick actions",
        "today.quick.subtitle": "Frequent actions in one tap",
        "today.quick.today": "Today",
        "today.quick.new": "New",
        "today.quick.done": "Done",
        "today.quick.eyes": "Eyes",

        "tasks.nav_title": "Tasks",
        "tasks.search_prompt": "Search tasks",
        "tasks.section_active": "Active",
        "tasks.section_done": "Completed",
        "tasks.control.summary": "Summary",
        "tasks.control.subtitle": "Active and completed tasks",
        "tasks.badge.active": "%d active",
        "tasks.badge.done": "%d done",
        "tasks.info.subtitle": "Manage priorities and keep your day in focus",
        "tasks.sort.by_due": "By due date",
        "tasks.sort.by_date": "By created date",
        "tasks.empty.title": "Nothing here yet",
        "tasks.empty.subtitle": "Create your first task to structure your day.",
        "tasks.empty.button": "Create task",
        "tasks.swipe.delete": "Delete",
        "tasks.swipe.restore": "Restore",
        "tasks.swipe.done": "Done",
        "tasks.menu.make_active": "Mark active",
        "tasks.menu.mark_done": "Mark done",
        "tasks.menu.edit": "Edit",
        "tasks.menu.delete": "Delete",
        "tasks.due.today": "Today %@",
        "tasks.due.tomorrow": "Tomorrow %@",

        "task_editor.main.title": "Main",
        "task_editor.main.subtitle": "Task title and notes",
        "task_editor.main.name": "Title",
        "task_editor.main.name_placeholder": "Example: Submit report",
        "task_editor.main.notes": "Notes",
        "task_editor.due.title": "Due date",
        "task_editor.due.subtitle": "Date and time",
        "task_editor.due.toggle": "Set due date",
        "task_editor.category.title": "Category",
        "task_editor.category.subtitle": "Task context",
        "task_editor.category.picker": "Category",
        "task_editor.nav.edit": "Edit",
        "task_editor.nav.new": "New task",
        "task_editor.cancel": "Cancel",
        "task_editor.save_changes": "Save changes",
        "task_editor.save": "Save",
        "task_editor.hero.edit": "Editing",
        "task_editor.hero.edit_subtitle": "Update details and keep your focus.",
        "task_editor.hero.new": "Create task",
        "task_editor.hero.new_subtitle": "Keep it short, you can add more later.",

        "pomodoro.nav_title": "Pomodoro",
        "pomodoro.hero.title": "Pomodoro",
        "pomodoro.round": "Round %d",
        "pomodoro.paused.title": "Paused",
        "pomodoro.paused.subtitle": "Ready to resume",
        "pomodoro.ready.title": "Ready to start",
        "pomodoro.ready.subtitle": "25 minutes of focus",
        "pomodoro.quick.title": "Quick start",
        "pomodoro.quick.subtitle": "Focus presets",
        "pomodoro.quick.break": "Break",
        "pomodoro.custom.title": "Custom timer",
        "pomodoro.custom.subtitle": "Manual session length",
        "pomodoro.custom.placeholder": "Min",
        "pomodoro.custom.minutes_unit": "min",
        "pomodoro.custom.start": "Start",
        "pomodoro.custom.range": "Range: 1-180 minutes",
        "pomodoro.transport.title": "Controls",
        "pomodoro.transport.subtitle": "Pause, resume, and stop",
        "pomodoro.transport.pause": "Pause",
        "pomodoro.transport.resume": "Resume",
        "pomodoro.transport.stop": "Stop",
        "pomodoro.remaining": "Left %d:%02d",
        "pomodoro.phase.focus": "Focus",
        "pomodoro.phase.short_break": "Break",
        "pomodoro.phase.long_break": "Long break",
        "pomodoro.phase.long_break_short": "Long",
        "pomodoro.phase.paused": "Paused",
        "pomodoro.phase.stopped": "Stopped",
        "pomodoro.notification.focus_body": "Time to focus",
        "pomodoro.notification.short_break_body": "Stretch and rest",
        "pomodoro.notification.long_break_body": "Breathe, walk, drink water",
        "pomodoro.alarm.title": "Timer finished",
        "pomodoro.alarm.subtitle": "Phase: %@",
        "pomodoro.alarm.stop": "Stop",

        "break.nav_title": "Break",
        "break.hero.title": "Break mini-game",
        "break.hero.subtitle": "Classic runner-style platformer",
        "break.hero.description": "Collect coins, jump over hazards, and reach the flag. A quick break between tasks.",
        "break.hud.record": "Record",
        "break.hud.goal": "Goal",
        "break.hud.goal_value": "12 coins",
        "break.hud.distance": "Distance",
        "break.hud.distance_value": "3400",
        "break.launch.title": "Launch mini-game",
        "break.launch.subtitle": "Opens in full screen",
        "break.launch.description": "Tap Launch to play in full-screen mode.",
        "break.launch.button": "Launch full screen",
        "break.hints.title": "How to play",
        "break.hints.subtitle": "Quick tips before start",
        "break.hints.step1": "1. Hold Left/Right to move.",
        "break.hints.step2": "2. Tap Jump to clear spikes and gaps.",
        "break.hints.step3": "3. Collect as many coins as possible and reach the flag.",
        "break.close": "Close",
        "break.hud.coins": "Coins",
        "break.hud.lives": "Lives",
        "break.hud.time": "Time",
        "break.hud.progress": "Progress",
        "break.reset": "Reset",
        "break.controls.left": "Left",
        "break.controls.right": "Right",
        "break.controls.jump": "Jump",
        "break.controls.play": "Play",
        "break.controls.pause": "Pause",
        "break.overlay.ready_title": "Ready to run",
        "break.overlay.paused_title": "Paused",
        "break.overlay.won_title": "Finish!",
        "break.overlay.lost_title": "Game over",
        "break.overlay.ready_subtitle": "Collect as many coins as possible and keep your lives.",
        "break.overlay.paused_subtitle": "You can continue or restart.",
        "break.overlay.won_subtitle": "Coins: %d/%d • Time: %@",
        "break.overlay.lost_subtitle": "Coins: %d/%d. Try again.",
        "break.overlay.start": "Start",
        "break.overlay.resume": "Resume",
        "break.overlay.play_again": "Play again",
        "break.breathing.title": "Breathing & recovery",
        "break.breathing.subtitle": "Smooth rhythm for calm focus",
        "break.breathing.description": "Pick a mode and follow the animation to lower tension, stabilize breathing, and recover faster.",
        "break.breathing.preset.balance": "Balanced",
        "break.breathing.preset.recovery": "Recovery",
        "break.breathing.phase.inhale": "Inhale",
        "break.breathing.phase.hold": "Hold",
        "break.breathing.phase.exhale": "Exhale",
        "break.breathing.phase.rest": "Rest",
        "break.breathing.hint.inhale": "Inhale through your nose with a soft chest rise.",
        "break.breathing.hint.hold": "Keep a gentle pause with no strain.",
        "break.breathing.hint.exhale": "Exhale slower than you inhaled.",
        "break.breathing.hint.rest": "Relax shoulders and jaw.",
        "break.breathing.cycle": "Cycle",
        "break.breathing.rate": "Rate",
        "break.breathing.rate_value": "%d bpm",
        "break.breathing.button.start": "Start",
        "break.breathing.button.pause": "Pause",
        "break.breathing.button.reset": "Reset",
        "health.analytics.title": "Breathing analytics",
        "health.analytics.subtitle": "Compact overview of your sessions",
        "health.analytics.sessions": "Sessions",
        "health.analytics.minutes": "Minutes",
        "health.analytics.avg_cycles": "Avg cycles",
        "health.analytics.this_week": "This week",
        "health.analytics.last_session": "Last session",
        "health.analytics.minutes_value": "%d min",
        "health.analytics.empty": "No data yet. Complete your first breathing session.",
        "health.voice.title": "Voice assistant",
        "health.voice.subtitle": "Spoken analytics and recommendations",
        "health.voice.description": "A short spoken report for breathing progress and practical next steps.",
        "health.voice.recommendations_title": "Recommendations",
        "health.voice.button.play": "Play analytics",
        "health.voice.button.stop": "Stop",
        "health.voice.status.ready": "Ready to speak",
        "health.voice.status.speaking": "Speaking now",
        "health.voice.disabled_hint": "Voice assistant is disabled. Enable it in Settings -> Health.",
        "health.voice.recommendation.first_session": "Start with 2-3 short sessions of 2-4 minutes each day.",
        "health.voice.recommendation.short_cycle": "Keep a steady rhythm: inhale for 4 seconds, exhale for 6.",
        "health.voice.recommendation.weekly_minutes": "Increase weekly breathing practice to at least 12-15 minutes.",
        "health.voice.recommendation.extend_exhale": "Try a slightly longer exhale to reduce tension faster.",
        "health.voice.recommendation.regularity": "Stay consistent: short daily sessions work better than rare long ones.",
        "health.voice.recommendation.keep_it_up": "Your current rhythm is solid. Keep practicing at similar times.",
        "health.voice.recommendation.progressive": "For extra progress, add one calm cycle to each session.",
        "health.voice.report.empty": "There is no breathing session data yet.",
        "health.voice.report.summary": "Overall: %d sessions, %d minutes, average %d cycles.",
        "health.voice.report.weekly": "This week: %d minutes of breathing practice.",
        "health.voice.report.last_session": "Last session: %@.",
        "health.voice.report.recommendations_intro": "Recommendations:",
        "health.voice.speed.calm": "Calm",
        "health.voice.speed.balanced": "Balanced",
        "health.voice.speed.energetic": "Energetic",
        "settings.voice.title": "Voice assistant",
        "settings.voice.subtitle": "Spoken analytics for the Health section",
        "settings.voice.enabled_title": "Enable assistant",
        "settings.voice.enabled_subtitle": "Use iPhone system voice for spoken reports",
        "settings.voice.auto_title": "Auto-play on open",
        "settings.voice.auto_subtitle": "Automatically read report when opening the Health tab",
        "settings.voice.speed_title": "Speech speed",
        "settings.voice.speed_subtitle": "Choose a comfortable pace",
        "settings.voice.model_title": "Voice model",
        "settings.voice.model_subtitle": "Choose a voice. Auto uses the most natural available option",
        "settings.voice.model_auto": "Auto (best available)",
        "settings.voice.preview": "Preview",
        "settings.voice.stop": "Stop",
        "settings.voice.preview_text": "Voice assistant preview. Analytics and recommendations will be read using the selected speed.",
        "settings.voice.disabled_hint": "Enable the assistant to unlock preview and auto-play.",

        "stats.metric.focus": "Focus",
        "stats.metric.tasks": "Tasks",
        "stats.metric.both": "Both",
        "stats.header.title": "Statistics",
        "stats.header.subtitle": "Focus and task trend",
        "stats.window.7": "7d",
        "stats.window.30": "30d",
        "stats.kpi.focus_minutes": "Focus, min",
        "stats.kpi.tasks": "Tasks",
        "stats.kpi.streak_days": "Streak days",
        "stats.kpi.avg_focus": "Avg focus",
        "stats.axis.date": "Date",
        "stats.axis.focus_minutes": "Focus, min",
        "stats.axis.tasks": "Tasks",
        "stats.axis.selected_date": "Selected date",
        "stats.footer.hint": "Tap chart to see day details",
        "stats.event.focus": "Focus",
        "stats.event.task_done": "Task",
        "stats.minutes": "%d min",
        "stats.hours": "%d h",
        "stats.hours_minutes": "%d h %d min",
        "stats.day.summary.focus_and_tasks": "%@ • %d done",
        "stats.day.summary.focus_only": "%@ focus",
        "stats.day.summary.tasks_only": "%d done",
        "stats.day.summary.none": "No activity",

        "countdown.default_title": "Event",
        "countdown.accessibility": "Countdown to event",
        "countdown.header.title": "Countdown to event",
        "countdown.header.subtitle": "Live timer to important date",
        "countdown.event_reached": "Event reached",
        "countdown.stats.days": "%d d",
        "countdown.stats.hours": "%d h",
        "countdown.actions.to_island": "To Island",
        "countdown.actions.reset": "Reset",
        "countdown.empty.title": "Countdown to event",
        "countdown.empty.subtitle": "No event set yet. Open Settings -> Event countdown.",

        "daily.default_title": "Work",
        "daily.notification.test_title": "Reminder test",
        "daily.notification.test_body": "This is a test notification",
        "daily.notification.work_title": "Time to work",
        "daily.notification.prep_title": "Get ready",
        "daily.notification.prep_body": "In %d min: %@",

        "task.notification.reminder": "Reminder",
        "movement.notification.title": "Movement break",
        "movement.tip.1": "Stand up, roll your shoulders 10 times, and stretch your neck.",
        "movement.tip.2": "Do 15 squats and walk 200 steps.",
        "movement.tip.3": "Breathe for 1 minute: 4-4-6, then stretch your back.",
        "movement.tip.4": "Rotate wrists and ankles 20 times.",
        "movement.tip.5": "30-second plank + water.",
        "movement.tip.fallback": "Stand up and move for a minute.",

        "task.category.work.title": "Work",
        "task.category.work.subtitle": "Focus and deadlines",
        "task.category.study.title": "Study",
        "task.category.study.subtitle": "Skills and growth",
        "task.category.health.title": "Health",
        "task.category.health.subtitle": "Body and energy",
        "task.category.rest.title": "Rest",
        "task.category.rest.subtitle": "Recovery",
        "task.category.home.title": "Home",
        "task.category.home.subtitle": "Household and order",
        "task.category.other.title": "Other",
        "task.category.other.subtitle": "Misc",

        "alarm.default_label": "Wake up",
        "alarm.notification.main_title": "Alarm",
        "alarm.notification.prep_title": "Alarm soon",
        "alarm.notification.prep_body": "In %d min: %@",
        "alarm.notification.test_title": "Alarm test",
        "alarm.notification.test_body": "This is a test notification",
        "alarm.settings.toggle": "Enable alarm",
        "alarm.settings.label_placeholder": "Label",
        "alarm.settings.time": "Time",
        "alarm.settings.prep": "Prepare in %d min",
        "alarm.settings.save": "Save and schedule",
        "alarm.settings.test": "Test in 3s",
        "alarm.settings.info": "You will get 1-2 notifications daily: Alarm soon (if enabled) and Alarm at selected time.",

        "settings.quick.title": "Quick actions",
        "settings.quick.subtitle": "Common scenarios in one tap",
        "settings.quick.reminders_on": "Reminders on",
        "settings.quick.reminders_off": "Reminders off",
        "settings.quick.reminders_subtitle": "Daily notifications",
        "settings.quick.eyes_on": "Eye training on",
        "settings.quick.eyes_off": "Eye training off",
        "settings.quick.eyes_subtitle": "Auto-suggest",
        "settings.quick.preset_title": "Preset 25/5/15",
        "settings.quick.preset_subtitle": "Classic Pomodoro",
        "settings.quick.test_title": "Notification test",
        "settings.quick.test_subtitle": "In 3 seconds",

        "settings.live.title": "Live Activities",
        "settings.live.subtitle": "Dynamic Island and active timers",
        "settings.live.end_all_title": "Close all activities",
        "settings.live.end_all_subtitle": "Remove all active timers",
        "settings.live.test_title": "Show 15s test",
        "settings.live.test_subtitle": "Dynamic Island rendering check",
        "settings.live.test_session_title": "Test",
        "settings.live.open_notifications_title": "Open notification settings",
        "settings.live.open_notifications_subtitle": "Permissions and banners",
        "settings.live.requirement": "Requires iPhone with Dynamic Island and Widget Extension installed.",
        "settings.live.ios_required": "Requires iOS 16.2+",
        "settings.scope.title": "Quick navigation",
        "settings.scope.subtitle": "Show only the sections you need",
        "settings.scope.all": "All",
        "settings.scope.account": "Profile",
        "settings.scope.focus": "Focus",
        "settings.scope.health": "Health",
        "settings.scope.data": "Data",

        "settings.pomodoro.title": "Pomodoro",
        "settings.pomodoro.subtitle": "Focus and break rhythm",
        "settings.pomodoro.focus_title": "Focus",
        "settings.pomodoro.focus_subtitle": "Main session",
        "settings.pomodoro.short_break_title": "Break",
        "settings.pomodoro.short_break_subtitle": "Short pause",
        "settings.pomodoro.long_break_title": "Long break",
        "settings.pomodoro.long_break_subtitle": "After focus streak",
        "settings.pomodoro.rounds_title": "Rounds to long break",
        "settings.pomodoro.rounds_subtitle": "Focus sessions in a row",
        "settings.pomodoro.ringtone_title": "Finish ringtone",
        "settings.pomodoro.ringtone_subtitle": "Sound when timer ends",
        "settings.pomodoro.ringtone_preview": "Preview",
        "settings.pomodoro.ringtone.radar": "Radar",
        "settings.pomodoro.ringtone.beacon": "Beacon",
        "settings.pomodoro.ringtone.chime": "Chime",
        "settings.pomodoro.ringtone.signal": "Signal",

        "settings.daily.title": "Daily reminders",
        "settings.daily.subtitle": "Scheduled automatic notifications",
        "settings.daily.toggle_title": "Enable",
        "settings.daily.toggle_subtitle": "Two notifications per day",
        "settings.daily.name_title": "Title (what to do)",
        "settings.daily.name_placeholder": "Example: Study / Workout / Work",
        "settings.daily.start_time": "Start time",
        "settings.daily.preparation": "Preparation",
        "settings.daily.preparation_value": "in %d min",
        "settings.daily.save": "Save and schedule",
        "settings.daily.test": "Test 3s",
        "settings.daily.info": "You will receive two notifications daily: Get ready in advance and Time to work at selected time.",

        "settings.eye.title": "Eye exercises",
        "settings.eye.subtitle": "Gentle prompts and training settings",
        "settings.eye.toggle_title": "Auto-suggest after long work",
        "settings.eye.toggle_subtitle": "Shows a soft prompt",
        "settings.eye.threshold": "Threshold",
        "settings.eye.threshold_value": "%d min in a row",
        "settings.eye.targets": "Targets per session",
        "settings.eye.limit": "Time limit per target",
        "settings.eye.cooldown": "Suggestion cooldown",
        "settings.eye.open_now": "Open training now",

        "settings.countdown.title": "Event countdown",
        "settings.countdown.subtitle": "Name and date of important event",
        "settings.countdown.hint": "Set an event to see live countdown on the main screen.",
        "settings.countdown.name_placeholder": "Event title",
        "settings.countdown.date_time": "Date and time",
        "settings.countdown.default_event_title": "Event",
        "settings.countdown.save": "Save",
        "settings.countdown.reset": "Reset",
        "settings.countdown.current": "Current event",
        "settings.countdown.current_value": "\"%@\" — %@",
        "settings.countdown.empty": "No event set",

        "settings.unit.minutes": "%d min",
        "settings.unit.seconds": "%d sec",

        "eye.mode.classic": "Classic",
        "eye.mode.moving": "Moving",
        "eye.mode.color": "Color",
        "eye.mode.peripheral": "Peripheral",
        "eye.mode.tracking": "Tracking",
        "eye.achievement.first_session": "First session",
        "eye.achievement.ten_hits_streak": "10 hits streak",
        "eye.achievement.sub_200ms": "Reaction < 200 ms",
        "eye.achievement.no_miss": "No misses",
        "eye.achievement.five_days": "5 days streak",
        "eye.achievement.pro_hawk": "Eagle eye",
        "eye.achievement.unlocked": "Unlocked",
        "eye.achievement.locked": "Locked",
        "eye.chart.empty": "No chart data",
        "eye.chart.not_available": "Charts not available",
        "eye.chart.session": "Session",
        "eye.chart.seconds": "s",
        "eye.common.done": "Done",
        "eye.common.cancel": "Cancel",
        "eye.common.save": "Save",
        "eye.common.em_dash": "—",
        "eye.unit.ms": "%d ms",

        "eye.game.title": "Eye trainer",
        "eye.game.streak": "Streak: %d",
        "eye.game.left_seconds": "%d s",
        "eye.game.intro.title": "Choose mode and tap Start",
        "eye.game.intro.subtitle": "Classic spawns a dot in random places. Other modes add movement, color, peripheral view, and tracking.",
        "eye.game.intro.targets": "%d targets",
        "eye.game.intro.seconds_per_target": "%d sec/target",
        "eye.game.break.title": "Eye break",
        "eye.game.break.subtitle": "Look far away through a window for 20 seconds. Blink often and make circular eye movements.",
        "eye.game.break.left": "Left: %d s",
        "eye.game.break.skip": "Skip",
        "eye.game.summary.title": "Done!",
        "eye.game.summary.hits_misses": "Hits: %d • Misses: %d",
        "eye.game.summary.reaction": "Avg reaction: %@ • Best: %@ • Best streak: %d",
        "eye.game.start": "Start",
        "eye.game.later": "Later",
        "eye.game.targets_progress": "Targets: %d/%d",
        "eye.game.hits": "Hits: %d",
        "eye.game.misses": "Misses: %d",
        "eye.game.resume": "Resume",
        "eye.game.pause": "Pause",
        "eye.game.finish": "Finish",
        "eye.game.again": "Again",
        "eye.game.done": "Done",

        "eye.home.nav_title": "Eyes",
        "eye.home.trainer_title": "Trainer",
        "eye.home.header_title": "Eye health",
        "eye.home.header_subtitle": "Focus, reaction, and fatigue prevention",
        "eye.home.goal_done": "Weekly goal completed",
        "eye.home.goal_left": "To goal: %d",
        "eye.home.metric_streak": "Streak",
        "eye.home.metric_week": "Week",
        "eye.home.metric_achievements": "Achievements",
        "eye.home.days_short": "%d d",
        "eye.home.week_activity": "Week activity",
        "eye.home.goal_done_subtitle": "Great! Weekly goal reached.",
        "eye.home.goal_remaining_subtitle": "%d sessions left to weekly goal.",
        "eye.home.quick_title": "Quick start",
        "eye.home.quick_subtitle": "Short session in one tap",
        "eye.home.settings": "Settings",
        "eye.home.quick_description": "A short session with %d targets. Consistency beats long sessions.",
        "eye.home.start_training": "Start training",
        "eye.home.stats": "Statistics",
        "eye.home.progress_title": "Progress",
        "eye.home.progress_subtitle": "Streak and reaction trend",
        "eye.home.streak_days": "Streak %d d.",
        "eye.home.last": "Last",
        "eye.home.hits": "hits",
        "eye.home.avg_reaction": "Average reaction",
        "eye.home.best_streak": "Best streak",
        "eye.home.in_row": "in a row",
        "eye.home.empty_training": "No sessions yet. Tap Start training.",
        "eye.home.achievements_title": "Achievements",
        "eye.home.achievements_subtitle": "Personal milestones",
        "eye.home.achievements_hint": "Unlock achievements with regular short sessions.",
        "eye.home.tips_title": "Tips",
        "eye.home.tips_subtitle": "Mini-habits against fatigue",
        "eye.home.tips_intro": "Small habits that noticeably reduce eye strain.",
        "eye.home.tip_1": "20-20-20 rule: every 20 minutes, look at something 20 feet away for 20 seconds.",
        "eye.home.tip_2": "Watch lighting: avoid glare and overly dim screens.",
        "eye.home.tip_3": "Blink more often to reduce dryness and strain.",
        "eye.home.tip_4": "Stretch shoulders and neck to improve blood flow.",

        "eye.stats.nav_title": "Statistics",
        "eye.stats.totals_title": "Totals",
        "eye.stats.totals_subtitle": "Overall training stats",
        "eye.stats.sessions": "Sessions",
        "eye.stats.hits": "Hits",
        "eye.stats.misses": "Misses",
        "eye.stats.best_streak": "Best streak",
        "eye.stats.avg_reaction": "Avg reaction",
        "eye.stats.sessions_title": "Sessions",
        "eye.stats.sessions_subtitle": "Recent launches history",
        "eye.stats.history_empty": "History is empty",
        "eye.stats.result": "Result %d/%d",
        "eye.stats.misses_value": "Misses %d",
        "eye.stats.streak_value": "Streak %d",
        "eye.stats.avg_value": "Avg %@",

        "eye.settings.nav_title": "Eye settings",
        "eye.settings.profile_title": "Training profile",
        "eye.settings.profile_subtitle": "You can change parameters anytime",
        "eye.settings.targets_value": "%d targets",
        "eye.settings.seconds_short_value": "%@ s",
        "eye.settings.session_title": "Session",
        "eye.settings.session_subtitle": "Base duration and target size",
        "eye.settings.targets_per_session": "Targets per session",
        "eye.settings.time_per_target": "Time per target",
        "eye.settings.dot_size": "Dot size",
        "eye.settings.adaptive_title": "Difficulty adaptation",
        "eye.settings.adaptive_subtitle": "Dynamic adjustment during session",
        "eye.settings.adaptive_toggle": "Enable adaptation",
        "eye.settings.adaptive_toggle_subtitle": "Increase difficulty on stable hits",
        "eye.settings.adaptive_step": "Adaptation step",
        "eye.settings.adaptive_step_value": "Every %d hits",
        "eye.settings.min_size": "Minimum size",
        "eye.settings.min_time": "Minimum time",
        "eye.settings.modes_title": "Modes",
        "eye.settings.modes_subtitle": "Mechanics available in training",
        "eye.settings.breaks_title": "Breaks",
        "eye.settings.breaks_subtitle": "Eye recovery between sets",
        "eye.settings.breaks_toggle": "Remind about breaks",
        "eye.settings.breaks_toggle_subtitle": "Pause after set number of targets",
        "eye.settings.breaks_frequency": "Break frequency",
        "eye.settings.breaks_frequency_value": "Every %d targets",
        "eye.settings.breaks_duration": "Duration",
        "eye.settings.seconds_value": "%d s",
        "eye.settings.auto_title": "Auto suggestion",
        "eye.settings.auto_subtitle": "Auto launch after focus",
        "eye.settings.auto_toggle": "Suggest after long work",
        "eye.settings.auto_toggle_subtitle": "Show a soft prompt",
        "eye.settings.auto_threshold": "Threshold",
        "eye.settings.auto_cooldown": "Repeat cooldown",
        "eye.settings.feedback_title": "Feedback",
        "eye.settings.feedback_subtitle": "Sound and haptics",
        "eye.settings.sound": "Sound",
        "eye.settings.haptics": "Haptics",
        "eye.settings.save_settings": "Save settings",

        "assistant.title": "Voice Assistant",
        "assistant.subtitle": "Control tasks and app features with your voice",
        "assistant.description": "Try commands like add task, open a section, start or stop pomodoro.",
        "assistant.state.ready": "Ready for commands",
        "assistant.state.listening": "Listening...",
        "assistant.state.processing": "Processing...",
        "assistant.state.speaking": "Speaking...",
        "assistant.state.error": "Error: %@",
        "assistant.transcript.title": "Recognized command",
        "assistant.transcript.empty": "Your command will appear here after recording.",
        "assistant.response.title": "Assistant response",
        "assistant.response.unknown": "I did not understand that command. Try: Open tasks.",
        "assistant.quick.title": "Quick commands",
        "assistant.quick.add": "Add task review inbox",
        "assistant.quick.tasks": "Open tasks",
        "assistant.quick.summary": "Weekly metrics summary",
        "assistant.quick.pomodoro": "Start pomodoro 25",
        "assistant.quick.pause": "Pause pomodoro",
        "assistant.quick.resume": "Resume pomodoro",
        "assistant.quick.break": "Start short break",
        "assistant.quick.eye": "Open eye exercise",
        "assistant.suggested.title": "Recommended for you",
        "assistant.suggested.personalized": "Personalized from your habits and recent actions.",
        "assistant.suggested.learning": "The assistant is learning your routines and will personalize suggestions soon.",
        "assistant.hint.tap_hold": "Tap the assistant button to start listening. Long press opens the full menu.",
        "assistant.button.start": "Start listening",
        "assistant.button.stop": "Done",
        "assistant.button.close": "Close",
        "assistant.permission.speech": "Allow speech recognition in iPhone Settings.",
        "assistant.permission.mic": "Allow microphone access in iPhone Settings.",
        "assistant.permission.unavailable": "Speech recognition is unavailable right now.",
        "assistant.response.task_added": "Added task: %@.",
        "assistant.response.task_completed": "Marked task as done: %@.",
        "assistant.response.task_deleted": "Deleted task: %@.",
        "assistant.response.task_not_found": "I could not find a matching task.",
        "assistant.response.tab_opened": "Opening section: %@.",
        "assistant.response.pomodoro_started": "Started focus for %d minutes.",
        "assistant.response.pomodoro_paused": "Pomodoro paused.",
        "assistant.response.pomodoro_resumed": "Pomodoro resumed.",
        "assistant.response.short_break_started": "Started a short break.",
        "assistant.response.long_break_started": "Started a long break.",
        "assistant.response.pomodoro_stopped": "Pomodoro stopped.",
        "assistant.response.eye_opened": "Opening eye exercise.",
        "assistant.response.metrics_today": "Today: %@ of focus and %d completed tasks.",
        "assistant.response.metrics_week": "Last 7 days: %@ of focus and %d completed tasks.",
        "assistant.response.metrics_active": "Active tasks right now: %d.",
        "assistant.response.metrics_streak": "Productive streak: %d days."
    ]
    private static let extraLooseDE: [String: String] = [
        "health.analytics.title": "Atem-Analyse",
        "health.analytics.subtitle": "Kompakte Ubersicht deiner Sitzungen",
        "health.analytics.sessions": "Sitzungen",
        "health.analytics.minutes": "Minuten",
        "health.analytics.avg_cycles": "Durchschn. Zyklen",
        "health.analytics.this_week": "Diese Woche",
        "health.analytics.last_session": "Letzte Sitzung",
        "health.analytics.minutes_value": "%d Min.",
        "health.analytics.empty": "Noch keine Daten. Starte deine erste Atemsitzung.",
        "health.voice.title": "Sprachassistent",
        "health.voice.subtitle": "Gesprochene Analyse und Empfehlungen",
        "health.voice.description": "Kurzer Sprachbericht zu deiner Atmung mit klaren nachsten Schritten.",
        "health.voice.recommendations_title": "Empfehlungen",
        "health.voice.button.play": "Analyse abspielen",
        "health.voice.button.stop": "Stopp",
        "health.voice.status.ready": "Bereit zum Sprechen",
        "health.voice.status.speaking": "Spricht gerade",
        "health.voice.disabled_hint": "Sprachassistent ist deaktiviert. Aktiviere ihn in Einstellungen -> Gesundheit.",
        "health.voice.recommendation.first_session": "Starte mit 2-3 kurzen Sitzungen von 2-4 Minuten pro Tag.",
        "health.voice.recommendation.short_cycle": "Halte einen ruhigen Rhythmus: 4 Sekunden ein, 6 Sekunden aus.",
        "health.voice.recommendation.weekly_minutes": "Erhohe dein Wochenziel auf mindestens 12-15 Minuten Atempraxis.",
        "health.voice.recommendation.extend_exhale": "Verlangere die Ausatmung leicht, um Spannung schneller zu senken.",
        "health.voice.recommendation.regularity": "Bleib regelmassig: kurze tagliche Sitzungen wirken besser.",
        "health.voice.recommendation.keep_it_up": "Dein aktueller Rhythmus ist gut. Bleib bei dieser Routine.",
        "health.voice.recommendation.progressive": "Fur mehr Fortschritt, fuhre pro Sitzung einen ruhigen Zyklus extra aus.",
        "health.voice.report.empty": "Noch keine Daten fur Atemsitzungen vorhanden.",
        "health.voice.report.summary": "Gesamt: %d Sitzungen, %d Minuten, durchschnittlich %d Zyklen.",
        "health.voice.report.weekly": "Diese Woche: %d Minuten Atempraxis.",
        "health.voice.report.last_session": "Letzte Sitzung: %@.",
        "health.voice.report.recommendations_intro": "Empfehlungen:",
        "health.voice.speed.calm": "Ruhig",
        "health.voice.speed.balanced": "Standard",
        "health.voice.speed.energetic": "Schnell",
        "settings.voice.title": "Sprachassistent",
        "settings.voice.subtitle": "Gesprochene Analyse im Gesundheitsbereich",
        "settings.voice.enabled_title": "Assistent aktivieren",
        "settings.voice.enabled_subtitle": "iPhone-Systemstimme fur Sprachberichte verwenden",
        "settings.voice.auto_title": "Automatisch beim Offnen",
        "settings.voice.auto_subtitle": "Bericht beim Offnen des Gesundheit-Tabs automatisch vorlesen",
        "settings.voice.speed_title": "Sprechtempo",
        "settings.voice.speed_subtitle": "Wahle ein angenehmes Tempo",
        "settings.voice.model_title": "Sprachmodell",
        "settings.voice.model_subtitle": "Stimme auswahlen. Auto nutzt die naturlichste verfugbare Option",
        "settings.voice.model_auto": "Auto (beste verfugbare)",
        "settings.voice.preview": "Vorschau",
        "settings.voice.stop": "Stopp",
        "settings.voice.preview_text": "Sprachassistent-Test. Analyse und Empfehlungen werden im gewahlten Tempo vorgelesen.",
        "settings.voice.disabled_hint": "Aktiviere den Assistenten fur Vorschau und automatische Wiedergabe.",
        "assistant.title": "Sprachassistent",
        "assistant.subtitle": "Aufgaben und App-Funktionen per Stimme steuern",
        "assistant.description": "Nutze Befehle wie Aufgabe erstellen, Bereich offnen oder Pomodoro starten.",
        "assistant.state.ready": "Bereit fur Befehle",
        "assistant.state.listening": "Ich hore zu...",
        "assistant.state.processing": "Verarbeite...",
        "assistant.state.speaking": "Antworte...",
        "assistant.state.error": "Fehler: %@",
        "assistant.transcript.title": "Erkannter Befehl",
        "assistant.transcript.empty": "Der erkannte Befehl erscheint hier.",
        "assistant.response.title": "Antwort",
        "assistant.response.unknown": "Befehl nicht verstanden. Versuch: Offne Aufgaben.",
        "assistant.quick.title": "Schnellbefehle",
        "assistant.quick.add": "Aufgabe erstellen Inbox pruefen",
        "assistant.quick.tasks": "Offne Aufgaben",
        "assistant.quick.summary": "Wochenstatistik",
        "assistant.quick.pomodoro": "Starte Pomodoro 25",
        "assistant.quick.pause": "Pomodoro pausieren",
        "assistant.quick.resume": "Pomodoro fortsetzen",
        "assistant.quick.break": "Kurze Pause starten",
        "assistant.quick.eye": "Offne Augen Training",
        "assistant.suggested.title": "Empfehlungen fur dich",
        "assistant.suggested.personalized": "Basierend auf deinen Gewohnheiten und letzten Aktionen.",
        "assistant.suggested.learning": "Der Assistent lernt deine Routinen und personalisiert Vorschlage in Kurze.",
        "assistant.hint.tap_hold": "Tippen startet die Aufnahme. Gedruckt halten offnet das volle Menu.",
        "assistant.button.start": "Aufnahme starten",
        "assistant.button.stop": "Fertig",
        "assistant.button.close": "Schliessen",
        "assistant.permission.speech": "Aktiviere Spracherkennung in den iPhone-Einstellungen.",
        "assistant.permission.mic": "Aktiviere Mikrofonzugriff in den iPhone-Einstellungen.",
        "assistant.permission.unavailable": "Spracherkennung ist derzeit nicht verfugbar.",
        "assistant.response.task_added": "Aufgabe hinzugefugt: %@.",
        "assistant.response.task_completed": "Aufgabe als erledigt markiert: %@.",
        "assistant.response.task_deleted": "Aufgabe geloscht: %@.",
        "assistant.response.task_not_found": "Keine passende Aufgabe gefunden.",
        "assistant.response.tab_opened": "Bereich wird geoffnet: %@.",
        "assistant.response.pomodoro_started": "Fokus fur %d Minuten gestartet.",
        "assistant.response.pomodoro_paused": "Pomodoro pausiert.",
        "assistant.response.pomodoro_resumed": "Pomodoro wird fortgesetzt.",
        "assistant.response.short_break_started": "Kurze Pause gestartet.",
        "assistant.response.long_break_started": "Lange Pause gestartet.",
        "assistant.response.pomodoro_stopped": "Pomodoro gestoppt.",
        "assistant.response.eye_opened": "Augentraining wird geoffnet.",
        "assistant.response.metrics_today": "Heute: %@ Fokus und %d erledigte Aufgaben.",
        "assistant.response.metrics_week": "Letzte 7 Tage: %@ Fokus und %d erledigte Aufgaben.",
        "assistant.response.metrics_active": "Aktive Aufgaben jetzt: %d.",
        "assistant.response.metrics_streak": "Produktive Serie: %d Tage."
    ]
    private static let extraLooseES: [String: String] = [
        "health.analytics.title": "Analitica de respiracion",
        "health.analytics.subtitle": "Resumen compacto de tus sesiones",
        "health.analytics.sessions": "Sesiones",
        "health.analytics.minutes": "Minutos",
        "health.analytics.avg_cycles": "Ciclos prom.",
        "health.analytics.this_week": "Esta semana",
        "health.analytics.last_session": "Ultima sesion",
        "health.analytics.minutes_value": "%d min",
        "health.analytics.empty": "Aun no hay datos. Completa tu primera sesion de respiracion.",
        "health.voice.title": "Asistente de voz",
        "health.voice.subtitle": "Analitica y recomendaciones por voz",
        "health.voice.description": "Un reporte breve por voz sobre tu progreso de respiracion y siguientes pasos.",
        "health.voice.recommendations_title": "Recomendaciones",
        "health.voice.button.play": "Reproducir analitica",
        "health.voice.button.stop": "Detener",
        "health.voice.status.ready": "Listo para hablar",
        "health.voice.status.speaking": "Reproduciendo voz",
        "health.voice.disabled_hint": "El asistente de voz esta desactivado. Activalo en Ajustes -> Salud.",
        "health.voice.recommendation.first_session": "Empieza con 2-3 sesiones cortas de 2-4 minutos al dia.",
        "health.voice.recommendation.short_cycle": "Manten un ritmo estable: inhala 4 segundos y exhala 6.",
        "health.voice.recommendation.weekly_minutes": "Aumenta la practica semanal a por lo menos 12-15 minutos.",
        "health.voice.recommendation.extend_exhale": "Prueba una exhalacion un poco mas larga para bajar la tension.",
        "health.voice.recommendation.regularity": "Se constante: sesiones cortas diarias funcionan mejor.",
        "health.voice.recommendation.keep_it_up": "Tu ritmo actual es bueno. Manten la misma rutina.",
        "health.voice.recommendation.progressive": "Para avanzar mas, agrega un ciclo calmado extra en cada sesion.",
        "health.voice.report.empty": "Todavia no hay datos de sesiones de respiracion.",
        "health.voice.report.summary": "Total: %d sesiones, %d minutos, promedio de %d ciclos.",
        "health.voice.report.weekly": "Esta semana: %d minutos de practica de respiracion.",
        "health.voice.report.last_session": "Ultima sesion: %@.",
        "health.voice.report.recommendations_intro": "Recomendaciones:",
        "health.voice.speed.calm": "Calma",
        "health.voice.speed.balanced": "Equilibrada",
        "health.voice.speed.energetic": "Rapida",
        "settings.voice.title": "Asistente de voz",
        "settings.voice.subtitle": "Analitica hablada para la seccion Salud",
        "settings.voice.enabled_title": "Activar asistente",
        "settings.voice.enabled_subtitle": "Usar la voz del sistema del iPhone para reportes",
        "settings.voice.auto_title": "Auto lectura al abrir",
        "settings.voice.auto_subtitle": "Leer el reporte automaticamente al abrir la pestana Salud",
        "settings.voice.speed_title": "Velocidad de voz",
        "settings.voice.speed_subtitle": "Elige un ritmo comodo",
        "settings.voice.model_title": "Modelo de voz",
        "settings.voice.model_subtitle": "Elige una voz. Auto usa la opcion mas natural disponible",
        "settings.voice.model_auto": "Auto (mejor disponible)",
        "settings.voice.preview": "Vista previa",
        "settings.voice.stop": "Detener",
        "settings.voice.preview_text": "Prueba del asistente de voz. La analitica y recomendaciones se leeran con la velocidad elegida.",
        "settings.voice.disabled_hint": "Activa el asistente para habilitar vista previa y auto lectura.",
        "assistant.title": "Asistente de voz",
        "assistant.subtitle": "Controla tareas y funciones con tu voz",
        "assistant.description": "Usa comandos como crear tarea, abrir una seccion o iniciar pomodoro.",
        "assistant.state.ready": "Listo para comandos",
        "assistant.state.listening": "Escuchando...",
        "assistant.state.processing": "Procesando...",
        "assistant.state.speaking": "Hablando...",
        "assistant.state.error": "Error: %@",
        "assistant.transcript.title": "Comando reconocido",
        "assistant.transcript.empty": "El comando aparecera aqui despues de grabar.",
        "assistant.response.title": "Respuesta del asistente",
        "assistant.response.unknown": "No entendi ese comando. Prueba: Abrir tareas.",
        "assistant.quick.title": "Comandos rapidos",
        "assistant.quick.add": "Crear tarea revisar correo",
        "assistant.quick.tasks": "Abrir tareas",
        "assistant.quick.summary": "Resumen de metricas",
        "assistant.quick.pomodoro": "Iniciar pomodoro 25",
        "assistant.quick.pause": "Pausar pomodoro",
        "assistant.quick.resume": "Reanudar pomodoro",
        "assistant.quick.break": "Iniciar descanso corto",
        "assistant.quick.eye": "Abre ejercicio de ojos",
        "assistant.suggested.title": "Recomendado para ti",
        "assistant.suggested.personalized": "Personalizado segun tus habitos y acciones recientes.",
        "assistant.suggested.learning": "El asistente esta aprendiendo tu rutina y pronto personalizara sugerencias.",
        "assistant.hint.tap_hold": "Toca el boton del asistente para grabar. Manten pulsado para abrir el menu completo.",
        "assistant.button.start": "Empezar escucha",
        "assistant.button.stop": "Listo",
        "assistant.button.close": "Cerrar",
        "assistant.permission.speech": "Activa el reconocimiento de voz en Ajustes del iPhone.",
        "assistant.permission.mic": "Activa el acceso al microfono en Ajustes del iPhone.",
        "assistant.permission.unavailable": "El reconocimiento de voz no esta disponible ahora.",
        "assistant.response.task_added": "Tarea agregada: %@.",
        "assistant.response.task_completed": "Tarea marcada como completada: %@.",
        "assistant.response.task_deleted": "Tarea eliminada: %@.",
        "assistant.response.task_not_found": "No encontre una tarea que coincida.",
        "assistant.response.tab_opened": "Abriendo seccion: %@.",
        "assistant.response.pomodoro_started": "Foco iniciado por %d minutos.",
        "assistant.response.pomodoro_paused": "Pomodoro en pausa.",
        "assistant.response.pomodoro_resumed": "Pomodoro reanudado.",
        "assistant.response.short_break_started": "Descanso corto iniciado.",
        "assistant.response.long_break_started": "Descanso largo iniciado.",
        "assistant.response.pomodoro_stopped": "Pomodoro detenido.",
        "assistant.response.eye_opened": "Abriendo ejercicio de ojos.",
        "assistant.response.metrics_today": "Hoy: %@ de foco y %d tareas completadas.",
        "assistant.response.metrics_week": "Ultimos 7 dias: %@ de foco y %d tareas completadas.",
        "assistant.response.metrics_active": "Tareas activas ahora: %d.",
        "assistant.response.metrics_streak": "Racha productiva: %d dias."
    ]
}
